## 논리 게이트 구현1

In [1]:
# AND 게이트 구현 예
def AND_gate(x1, x2):
    w1 = 1
    w2 = 1
    b = -1
    result = w1*x1 + w2*x2 + b

    if result <= 0:
        return 0
    else:
        return 1

In [2]:
# NAND 게이트 구현 예
def NAND_gate(x1, x2):
    w1 = -0.5
    w2 = -0.5
    b = 1
    result = w1*x1 + w2*x2 + b

    if result <= 0:
        return 0
    else:
        return 1

In [3]:
# OR 게이트 구현 예
def OR_gate(x1, x2):
    w1 = 1
    w2 = 1
    b = -0.5
    result = w1*x1 + w2*x2 + b

    if result <= 0:
        return 0
    else:
        return 1

In [4]:
# XOR 게이트 구현 예
def XOR_gate(x1, x2):
    z1 = NAND_gate(x1, x2)
    z2 = OR_gate(x1, x2)
    y = AND_gate(z1, z2)

    return y

In [5]:
print("AND gate")
for xs in [(0, 0), (0, 1), (1, 0), (1, 1)]:
    y = AND_gate(xs[0], xs[1])
    print(str(xs) + "->" + str(y))

AND gate
(0, 0)->0
(0, 1)->0
(1, 0)->0
(1, 1)->1


In [6]:
print("NAND gate")
for xs in [(0, 0), (0, 1), (1, 0), (1, 1)]:
    y = ＮAND_gate(xs[0], xs[1])
    print(str(xs) + "->" + str(y))

NAND gate
(0, 0)->1
(0, 1)->1
(1, 0)->1
(1, 1)->0


In [7]:
print("OR gate")
for xs in [(0, 0), (0, 1), (1, 0), (1, 1)]:
    y = OR_gate(xs[0], xs[1])
    print(str(xs) + "->" + str(y))

OR gate
(0, 0)->0
(0, 1)->1
(1, 0)->1
(1, 1)->1


In [8]:
print("XOR gate")
for xs in [(0, 0), (0, 1), (1, 0), (1, 1)]:
    y = XOR_gate(xs[0], xs[1])
    print(str(xs) + "->" + str(y))

XOR gate
(0, 0)->0
(0, 1)->1
(1, 0)->1
(1, 1)->0


## 논리 게이트 구현2

In [9]:
# 도구 임포트
import torch
import torch.nn as nn

# GPU 연산이 가능할 경우 GPU 연산 수행
device = 'cuda' if torch.cuda.is_available() else 'cpu'
torch.manual_seed(777)
if device == 'cuda':
    toch.cuda.manual_seed_all(777)

# 각gate문제에해당하는입력과출력정의
X = torch.FloatTensor([[0, 0], [0, 1], [1, 0], [1, 1]]).to(device)
Y = torch.FloatTensor([[0], [0], [0], [1]]).to(device) #AND
# Y=torch.FloatTensor([[1], [1], [1], [0]]).to(device) #NAND
# Y=torch.FloatTensor([[0], [1], [1], [1]]).to(device) #OR
# Y=torch.FloatTensor([[0], [1], [1], [0]]).to(device) #XOR

# 단층 퍼셉트론 설계
linear = nn.Linear(2, 1, bias=True)
sigmoid = nn.Sigmoid()
model = nn.Sequential(linear, sigmoid).to(device)

# 이진 분류 문제이므로 비용 함수로 크로스엔트로피 함수 사용
# nn.BCELoss() - 이진 분류에서 사용하는 크로스엔트로피 함수

# 비용 함수와 옵티마이저 정의
criterion = torch.nn.BCELoss().to(device)
optimizer = torch.optim.SGD(model.parameters(), lr=1)

#반복학습수행
for step in range(1001):
    optimizer.zero_grad()
    hypothesis = model(X)
    
    #비용함수
    cost = criterion(hypothesis, Y)
    cost.backward()
    optimizer.step()
 
    if step % 100 == 0:  # 100번째 에포크마다 비용 출력
        print(step, cost.item())
        
print('\n\n')
print('hypothesis값 : ')
print(hypothesis)

print('\n')
predicted = (hypothesis > 0.5).float()
print('예측값 : ')
print(predicted)

print('\n')
print('실제값 : ')
print(Y)

C:\Users\PC\anaconda3\Lib\site-packages\torch\utils\_pytree.py:185: FutureWarning: optree is installed but the version is too old to support PyTorch Dynamo in C++ pytree. C++ pytree support is disabled. Please consider upgrading optree using `python3 -m pip install --upgrade 'optree>=0.13.0'`.
  warnings.warn(


0 0.6932064294815063
100 0.14414836466312408
200 0.0817771703004837
300 0.05658476799726486
400 0.04307378828525543
500 0.03469350188970566
600 0.029005466029047966
700 0.024899723008275032
800 0.021800503134727478
900 0.01938023790717125
1000 0.01743890717625618



hypothesis값 : 
tensor([[1.2500e-05],
        [2.0266e-02],
        [2.0266e-02],
        [9.7162e-01]], grad_fn=<SigmoidBackward0>)


예측값 : 
tensor([[0.],
        [0.],
        [0.],
        [1.]])


실제값 : 
tensor([[0.],
        [0.],
        [0.],
        [1.]])


In [10]:
# 도구 임포트
import torch
import torch.nn as nn

# GPU 연산이 가능할 경우 GPU 연산 수행
device = 'cuda' if torch.cuda.is_available() else 'cpu'
torch.manual_seed(777)
if device == 'cuda':
    toch.cuda.manual_seed_all(777)

# 각gate문제에해당하는입력과출력정의
X = torch.FloatTensor([[0, 0], [0, 1], [1, 0], [1, 1]]).to(device)
#  = torch.FloatTensor([[0], [0], [0], [1]]).to(device) #AND
# Y=torch.FloatTensor([[1], [1], [1], [0]]).to(device) #NAND
# Y=torch.FloatTensor([[0], [1], [1], [1]]).to(device) #OR
Y=torch.FloatTensor([[0], [1], [1], [0]]).to(device) #XOR

# 단층 퍼셉트론 설계
linear1 = nn.Linear(2, 2, bias=True)
sigmoid1 = nn.Sigmoid()
linear2 = nn.Linear(2, 1, bias=True)
sigmoid2 = nn.Sigmoid()
model = nn.Sequential(linear1, sigmoid1, linear2, sigmoid2).to(device)

# 이진 분류 문제이므로 비용 함수로 크로스엔트로피 함수 사용
# nn.BCELoss() - 이진 분류에서 사용하는 크로스엔트로피 함수

# 비용 함수와 옵티마이저 정의
criterion = torch.nn.BCELoss().to(device)
optimizer = torch.optim.SGD(model.parameters(), lr=1)

#반복학습수행
for step in range(10001):
    optimizer.zero_grad()
    hypothesis = model(X)
    
    #비용함수
    cost = criterion(hypothesis, Y)
    cost.backward()
    optimizer.step()
 
    if step % 100 == 0:  # 100번째 에포크마다 비용 출력
        print(step, cost.item())
        
print('\n\n')
print('hypothesis값 : ')
print(hypothesis)

print('\n')
predicted = (hypothesis > 0.5).float()
print('예측값 : ')
print(predicted)

print('\n')
print('실제값 : ')
print(Y)

0 0.7434073090553284
100 0.693165123462677
200 0.6931577920913696
300 0.6931517124176025
400 0.6931463479995728
500 0.6931411027908325
600 0.693135678768158
700 0.6931294798851013
800 0.6931220889091492
900 0.6931126117706299
1000 0.6930999755859375
1100 0.6930823922157288
1200 0.6930569410324097
1300 0.6930190920829773
1400 0.6929606199264526
1500 0.6928660273551941
1600 0.6927032470703125
1700 0.6923960447311401
1800 0.6917301416397095
1900 0.6899653077125549
2000 0.6838314533233643
2100 0.6561663150787354
2200 0.43109801411628723
2300 0.13489243388175964
2400 0.06630408763885498
2500 0.04216805472970009
2600 0.030453797429800034
2700 0.023665882647037506
2800 0.01927771419286728
2900 0.01622401550412178
3000 0.01398373395204544
3100 0.012273895554244518
3200 0.010928076691925526
3300 0.009842460043728352
3400 0.008949019014835358
3500 0.00820132251828909
3600 0.007566746324300766
3700 0.0070216478779911995
3800 0.006548585370182991
3900 0.006134245544672012
4000 0.00576836708933115
